import os
import psycopg2
conn = psycopg2.connect(os.environ.get("SUPABASE_URI"))
cur = conn.cursor()
print('=== ULTIMAS 10 ENTRADAS (todas) ===')
cur.execute('''SELECT e.id, e.estado, e.preference_id, e.payment_order_id, e.payment_id, e.cantidad, e.total, e.creada_en, u.email FROM entradas e JOIN usuarios u ON e.usuario_id = u.id ORDER BY e.id DESC LIMIT 10''')
for r in cur.fetchall(): print(r)
print()
print('=== PENDIENTES CON payment_order_id ===')
cur.execute('''SELECT e.id, e.estado, e.preference_id, e.payment_order_id, e.cantidad, e.total, u.email FROM entradas e JOIN usuarios u ON e.usuario_id = u.id WHERE e.estado = %s AND e.payment_order_id IS NOT NULL ORDER BY e.id DESC''', ('pendiente',))
rows = cur.fetchall()
print('Cantidad:', len(rows))
for r in rows: print(r)
print()
print('=== PAGADAS SIN CODIGO GA- ===')
cur.execute('''SELECT e.id, e.estado, e.preference_id, e.payment_order_id, e.payment_id, e.total, u.email FROM entradas e JOIN usuarios u ON e.usuario_id = u.id WHERE e.estado = %s AND (e.preference_id IS NULL OR e.preference_id NOT LIKE %s) ORDER BY e.id DESC LIMIT 10''', ('pagada', 'GA-%'))
rows = cur.fetchall()
print('Cantidad:', len(rows))
for r in rows: print(r)
conn.close()
